export const dummyProfile = {
  fullName: "Yanche Kurniawan",
  username: "@yanchekurniawan",
  profileImg: "/avatars/boy1.png",
  coverImg: "/cover.png",
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  link: "https://yanchekurniawan.com",
  following: ["1", "2", "3"],
  followers: ["1", "2", "3"],
  verified: true,
};

export const trendsDummyData = [
  {
    location: "Indonesia",
    tag: "Wkwk",
    countPost: 50000,
  },
  {
    location: "Indonesia",
    tag: "Kominfo",
    countPost: 81000,
  },
  {
    location: "Indonesia",
    tag: "Ransomware",
    countPost: 73500,
  },
  {
    location: "Indonesia",
    tag: "Bali",
    countPost: 130000,
  },
];

export const whoToFollowDummy = [
  {
    img: "/avatars/boy2.png",
    fullName: "Alvyena",
    username: "@Alvyena",
    verified: true,
  },
  {
    img: "/avatars/boy3.png",
    fullName: "DumbBoys",
    username: "@DumbBoys",
    verified: false,
  },
  {
    img: "/avatars/girl1.png",
    fullName: "Cloud",
    username: "@Cloud",
    verified: false,
  },
];

export const postsDummyData = [
  {
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: "/posts/post1.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy1.png",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl1.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy2.png",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl2.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy3.png",
      fullName: "John Doe",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/post3.png",
    user: {
      username: "johndoe",
      profileImg: "/avatars/boy3.png",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/girl3.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const notifications = [
  {
    _id: "1",
    from: {
      _id: "1",
      fullname: "John Doe",
      profileImg: "/avatars/boy2.png",
    },
    type: "follow",
  },
  {
    _id: "2",
    from: {
      _id: "2",
      fullname: "Jane Doe",
      profileImg: "/avatars/girl1.png",
    },
    type: "like",
  },
];
